#!/usr/bin/env bash
# eBPF capture soak: prove heron's on-host SSL-uprobe path works end-to-end on
# the staging VM BEFORE prod is ever allowed to deploy it. Chains after
# deploy-staging (ci(main) -> deploy-staging -> ebpf-soak), mirroring
# staging-soak.yml/soak-staging.sh's VM-resolution + ssh model exactly.
#
# What it asserts (the eBPF path's whole value proposition):
#   1. The deployed binary is an eBPF build      (runtime-config.ebpf_available)
#   2. Uprobes actually attached to libssl       (ebpf_uprobes_attached >= 1)
#   3. Real SSL traffic was captured             (ebpf_events_received delta > 0)
#   4. Frames were synthesized into the pipeline (ebpf_frames_synthesized delta > 0)
#   5. The source attributed a process           (ebpf_process_cache_size >= 1)
#   6. The synthesized bytes parsed + persisted  (an LlmCall on /v1/chat/completions)
#
# Item 6 is the true end-to-end proof: plaintext lifted from the kernel ->
# synthetic TCP frames -> HTTP/LLM parse -> DuckDB row queryable over the API.
# Process attribution (the headline feature over a passive tap) is asserted via
# item 5 because the API list view doesn't surface process columns yet (storage
# persists them; surfacing is a later phase) — the process-cache gauge is the
# source-level signal that pid/comm resolution ran.
#
# Traffic is generated by ebpf_soak_gen.py (shipped alongside) using
# `openssl s_client` — see that file for why curl/Python ssl are unreliable
# probe triggers.
#
# Env (same family as soak-staging.sh):
#   HERON_STAGE_VM    REQUIRED  libvirt domain  (CI: repo Variable HERON_STAGE_VM)
#   HERON_STAGE_USER  REQUIRED  ssh login       (CI: repo Variable HERON_STAGE_USER)
#   HERON_STAGE_NET / HERON_STAGE_SSH_KEY       libvirt net + key
#                                               (default: default / ~/.ssh/id_ed25519)
#   HERON_STAGE_API_PORT   heron API port on the VM            (default 4500)
#   HERON_EBPF_REQUESTS    LLM-shaped requests to generate     (default 8)
#   HERON_EBPF_POLL_SECS   max seconds to wait for metrics+call (default 60)
#
# Exit: 0 all assertions passed · 1 an assertion failed (do NOT promote) ·
#       2 setup/env error (couldn't reach the VM / heron not up).
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

VM="${HERON_STAGE_VM:?set HERON_STAGE_VM (libvirt domain; CI passes vars.HERON_STAGE_VM)}"
SSH_USER="${HERON_STAGE_USER:?set HERON_STAGE_USER (VM ssh login; CI passes vars.HERON_STAGE_USER)}"
NET="${HERON_STAGE_NET:-default}"
SSH_KEY="${HERON_STAGE_SSH_KEY:-$HOME/.ssh/id_ed25519}"
API_PORT="${HERON_STAGE_API_PORT:-4500}"
REQUESTS="${HERON_EBPF_REQUESTS:-8}"
POLL_SECS="${HERON_EBPF_POLL_SECS:-60}"

SSH_OPTS=(-i "$SSH_KEY" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ConnectTimeout=8)
remote() { ssh "${SSH_OPTS[@]}" "$SSH_USER@$IP" "$@"; }

# Sum one internal metric across all pipelines + global. Reads the
# /api/internal-metrics JSON on stdin; prints an integer (0 if absent). Uses
# python3 (always on the runner — it runs the tara invariant tests) rather than
# jq, which the staging-deploy runner doesn't ship.
metric_value() {
  python3 -c '
import sys, json
name = sys.argv[1]
try:
    d = json.load(sys.stdin).get("data", {})
except Exception:
    print(0); sys.exit(0)
tot = 0
for p in d.get("pipelines", []):
    for m in p.get("metrics", []):
        if m.get("name") == name:
            tot += m.get("value", 0)
for m in d.get("global", {}).get("metrics", []):
    if m.get("name") == name:
        tot += m.get("value", 0)
print(tot)
' "$1"
}

json_field() { python3 -c 'import sys,json;print(json.load(sys.stdin).get("data",{}).get(sys.argv[1],""))' "$1"; }

echo "==> resolving $VM IP from libvirt '$NET' DHCP leases"
IP="$(sudo virsh net-dhcp-leases "$NET" 2>/dev/null | awk -v n="$VM" '$0 ~ n {print $5}' | cut -d/ -f1 | head -1)"
[ -n "$IP" ] || { echo "::error::no DHCP lease for domain '$VM' on net '$NET' — is the VM running?" >&2; exit 2; }
echo "    $VM -> $IP  (heron API :$API_PORT)"

API="http://localhost:$API_PORT"

# 1. heron must be up AND be an eBPF build. A non-eBPF binary rejects the ebpf
#    source in config.toml at startup, so heron would not be healthy — but check
#    ebpf_available explicitly so the failure message is unambiguous.
echo "==> waiting for heron health on the VM"
ok=0
for _ in $(seq 1 30); do
  if remote "curl -fsS $API/api/health" >/dev/null 2>&1; then ok=1; break; fi
  sleep 2
done
[ "$ok" = 1 ] || { echo "::error::heron did not become healthy on $API within 60s" >&2; exit 2; }

rc="$(remote "curl -fsS $API/api/runtime-config" 2>/dev/null || true)"
avail="$(printf '%s' "$rc" | json_field ebpf_available)"
if [ "$avail" != "True" ] && [ "$avail" != "true" ]; then
  echo "::error::deployed binary reports ebpf_available=$avail — it was NOT built with the \`ebpf\` feature. Build the staging artifact with --features \"console ebpf\" (see ci.yml)." >&2
  exit 1
fi
echo "    heron healthy; ebpf_available=true"

# 2. Baseline the cumulative counters before generating any traffic, so the
#    assertion is on the DELTA this soak caused (robust to a fresh restart that
#    zeroes them OR a prior run that didn't).
echo "==> snapshotting baseline eBPF metrics"
before="$(remote "curl -fsS $API/api/internal-metrics" 2>/dev/null || echo '{}')"
ev0="$(printf '%s' "$before" | metric_value ebpf_events_received)"
fr0="$(printf '%s' "$before" | metric_value ebpf_frames_synthesized)"
echo "    baseline: events_received=$ev0 frames_synthesized=$fr0"

# 3. Generate LLM-shaped TLS traffic on the VM (libssl via openssl s_client).
echo "==> generating $REQUESTS LLM-shaped TLS request(s) on the VM"
RD="/tmp/ebpf-soak.$$"
remote "mkdir -p $RD"
# shellcheck disable=SC2064
trap "ssh ${SSH_OPTS[*]} $SSH_USER@$IP 'rm -rf $RD' >/dev/null 2>&1 || true" EXIT
scp "${SSH_OPTS[@]}" "$HERE/ebpf_soak_gen.py" "$SSH_USER@$IP:$RD/" >/dev/null
gen="$(remote "python3 $RD/ebpf_soak_gen.py --requests $REQUESTS" 2>/dev/null || echo '{}')"
echo "    generator: $gen"
gen_ok="$(printf '%s' "$gen" | python3 -c 'import sys,json;print(json.load(sys.stdin).get("ok",False))' 2>/dev/null || echo False)"
if [ "$gen_ok" != "True" ]; then
  echo "::error::traffic generator failed to complete its requests (TLS stub unreachable / openssl missing?)" >&2
  exit 1
fi

# 4. Poll until the counters move AND a matching LlmCall lands (the synth ->
#    parse -> persist hop is async; give it room). `now` in SECONDS — the API's
#    time range is seconds-since-epoch (params.rs).
echo "==> polling for eBPF metrics + persisted LlmCall (<= ${POLL_SECS}s)"
start_win="$(( $(date +%s) - 600 ))"
attached=0; events=0; frames=0; pcache=0; calls=0
deadline=$(( $(date +%s) + POLL_SECS ))
while [ "$(date +%s)" -lt "$deadline" ]; do
  snap="$(remote "curl -fsS $API/api/internal-metrics" 2>/dev/null || echo '{}')"
  attached="$(printf '%s' "$snap" | metric_value ebpf_uprobes_attached)"
  events="$(printf '%s' "$snap" | metric_value ebpf_events_received)"
  frames="$(printf '%s' "$snap" | metric_value ebpf_frames_synthesized)"
  pcache="$(printf '%s' "$snap" | metric_value ebpf_process_cache_size)"

  end_win="$(date +%s)"
  callq="$(remote "curl -fsS '$API/api/llm-calls?start=$start_win&end=$end_win&page=1&page_size=5&request_path=%2Fv1%2Fchat%2Fcompletions'" 2>/dev/null || echo '{}')"
  calls="$(printf '%s' "$callq" | python3 -c 'import sys,json;print(json.load(sys.stdin).get("data",{}).get("total",0))' 2>/dev/null || echo 0)"

  if [ "$attached" -ge 1 ] && [ "$events" -gt "$ev0" ] && [ "$frames" -gt "$fr0" ] && [ "$pcache" -ge 1 ] && [ "$calls" -ge 1 ]; then
    break
  fi
  sleep 3
done

echo "==> verdict:"
echo "    ebpf_uprobes_attached   = $attached   (want >= 1)"
echo "    ebpf_events_received    = $events     (want > $ev0)"
echo "    ebpf_frames_synthesized = $frames     (want > $fr0)"
echo "    ebpf_process_cache_size = $pcache     (want >= 1)"
echo "    LlmCall(/v1/chat/completions) total = $calls   (want >= 1)"

fail=0
[ "$attached" -ge 1 ]        || { echo "::error::no uprobes attached — libssl not found or attach failed"; fail=1; }
[ "$events" -gt "$ev0" ]     || { echo "::error::no new SSL events captured — uprobe never fired"; fail=1; }
[ "$frames" -gt "$fr0" ]     || { echo "::error::no frames synthesized — capture produced no pipeline input"; fail=1; }
[ "$pcache" -ge 1 ]          || { echo "::error::process cache empty — no pid/comm attribution"; fail=1; }
[ "$calls" -ge 1 ]           || { echo "::error::no LlmCall persisted — synth->parse->persist broke"; fail=1; }

if [ "$fail" = 0 ]; then
  echo "==> eBPF SOAK PASS — on-host SSL capture works end-to-end; safe to promote"
  exit 0
fi
echo "::error::eBPF SOAK FAILED — do NOT promote this build to prod"
exit 1
