use std::collections::HashMap;
use std::fmt;
use std::net::IpAddr;
use std::sync::{Arc, RwLock};

/// Composite key identifying a single in-flight turn.
///
/// For Codex (explicit turn_id): both fields are Some.
/// For Anthropic (implicit): turn_id is generated by TurnTracker on turn start;
/// session_id comes from the X-Claude-Code-Session-Id header.
#[derive(Debug, Clone, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct TurnKey {
    pub source_id: String,
    pub session_id: String,
    pub turn_id: String,
}

/// Lifecycle state of an agent turn. Three states:
///
/// * `InProgress` — at least one call has been ingested for this turn, no
///   wire-level terminal has landed yet. Lives only in the in-memory
///   [`ActiveTurnRegistry`]; never written to the `agent_turns` table.
/// * `Complete` — a main-agent terminal call (e.g. `end_turn`,
///   `max_tokens`, `refusal`) landed and the buffer's grace window expired.
///   Persisted to the `agent_turns` table.
/// * `Incomplete` — buffer drained without a terminal (idle timeout, pcap
///   EOF, server shutdown, RST mid-stream). Persisted to `agent_turns`.
///
/// The wire-level reason (e.g. `end_turn`) lives separately in
/// `final_finish_reason: Option<String>`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TurnStatus {
    InProgress,
    Complete,
    Incomplete,
}

impl fmt::Display for TurnStatus {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            TurnStatus::InProgress => write!(f, "in_progress"),
            TurnStatus::Complete => write!(f, "complete"),
            TurnStatus::Incomplete => write!(f, "incomplete"),
        }
    }
}

/// In-memory registry of currently-in-flight agent turns, keyed by
/// `turn_id`. Each `TurnTracker` writes a snapshot here on every ingest
/// (replacing any prior snapshot for the same turn_id), and removes the
/// entry when the turn finalizes. The `ts-api` `/api/agent-turns` handler
/// reads this registry, filters by the requested time window, and unions
/// the result with rows persisted in DuckDB so the console sees both
/// in-progress and finalized turns in one list.
///
/// Why a registry instead of writing to DuckDB on every call:
/// * On a busy capbench run (100 concurrent agents × 50 calls/turn) the
///   per-call DB upsert path would cost ~50 000 writes per session.
///   HashMap insert is ~100 ns; DuckDB upsert is ~5 ms. Same visibility
///   guarantee, no write amplification.
/// * The `agent_turns` table stays the canonical source of truth for
///   *finalized* turns (clean SQL semantics; survives restart). The
///   registry is a short-lived "currently observable" view layered on
///   top of it.
///
/// A server restart loses the registry; in-progress turns vanish from
/// `/api/agent-turns` until either the next ingest re-creates them or
/// the turn finalizes and writes to DuckDB. This matches the existing
/// in-memory `SessionBuffer` behavior — both were already RAM-only.
pub type ActiveTurnRegistry = Arc<RwLock<HashMap<String, AgentTurn>>>;

/// Construct an empty `ActiveTurnRegistry` ready to share between
/// trackers and the API.
pub fn new_active_turn_registry() -> ActiveTurnRegistry {
    Arc::new(RwLock::new(HashMap::new()))
}

/// Aggregated record for one agent turn (user input → final assistant output).
#[derive(Debug, Clone)]
pub struct AgentTurn {
    pub source_id: String,
    pub turn_id: String,
    pub session_id: String,
    pub wire_api: String,   // copied from LlmCall.wire_api
    pub agent_kind: String, // "claude-cli" / "codex-cli" / ...

    /// Representative IPs captured from the turn's first `LlmCall`. A turn is
    /// almost always one client→one server within a single connection; if it
    /// spans more, drill into the per-call list to see them all.
    pub client_ip: IpAddr,
    pub server_ip: IpAddr,

    pub start_time_us: i64, // first call's request_time
    pub end_time_us: i64,   // last call's complete_time (or request_time if no resp)
    pub duration_ms: u64,   // (end_time_us - start_time_us) / 1000

    pub call_count: u32,
    pub models_used: Vec<String>,    // ordered appearance, deduped
    pub subagents_used: Vec<String>, // ordered appearance, deduped; empty if none

    pub total_input_tokens: u64,
    pub total_output_tokens: u64,
    pub total_cache_read_input_tokens: u64,
    pub total_cache_creation_input_tokens: u64,
    pub total_cost_usd: Option<f64>, // None when pricing unknown

    pub status: TurnStatus,
    pub final_finish_reason: Option<String>, // raw provider finish_reason of last call

    /// Up to ~500 chars of the user prompt that opened this turn. Full body
    /// lives on the `llm_calls` row pointed at by `user_call_id`.
    pub user_input_preview: Option<String>,
    /// LlmCall.id of the call whose request body carried the opening user
    /// prompt. `None` when profile could not extract user input.
    pub user_call_id: Option<String>,
    /// Up to ~500 chars of the final assistant text. Full body lives on
    /// `llm_calls` pointed at by `final_call_id`.
    pub final_answer_preview: Option<String>,
    /// LlmCall.id of the call that produced the terminating response.
    pub final_call_id: Option<String>,

    /// Ordered list of `LlmCall.id` values that belong to this turn.
    /// Populated by `TurnTracker::ingest` in ingest order. Replaces the
    /// Phase-1 `LlmCall.turn_id` back-reference.
    pub call_ids: Vec<String>,

    pub metadata: serde_json::Value, // future extension point; empty object by default

    // --- Agent rollup fields (populated by Task 14; defaults at construction) ---
    /// Deduplicated set of tool surfaces observed across all calls in this turn.
    pub tool_surfaces: Vec<ts_common::agent::ToolSurface>,
    /// Total number of tool calls across all calls in this turn.
    pub tool_call_total: u32,
    /// Topology inferred for this turn (single-agent / sub-agent / orchestrator).
    pub agent_topology: Option<ts_common::agent::AgentTopology>,
    /// Tool calls flagged as suspicious during rollup analysis.
    pub suspicious_skills: Vec<crate::SuspiciousSkillRollup>,
}

impl fmt::Display for AgentTurn {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            f,
            "[AgentTurn] turn={} session={} agent={} calls={} dur={}ms status={}",
            self.turn_id,
            self.session_id,
            self.agent_kind,
            self.call_count,
            self.duration_ms,
            self.status,
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use ts_llm::wire_apis as wa;

    #[test]
    fn turn_key_equality_and_hash() {
        use std::collections::HashSet;
        let k1 = TurnKey {
            source_id: String::new(),
            session_id: "s".into(),
            turn_id: "t".into(),
        };
        let k2 = TurnKey {
            source_id: String::new(),
            session_id: "s".into(),
            turn_id: "t".into(),
        };
        let mut set = HashSet::new();
        set.insert(k1.clone());
        assert!(set.contains(&k2));
    }

    #[test]
    fn status_display() {
        assert_eq!(TurnStatus::Complete.to_string(), "complete");
        assert_eq!(TurnStatus::Incomplete.to_string(), "incomplete");
    }

    #[test]
    fn agent_turn_display_includes_key_fields() {
        let turn = AgentTurn {
            source_id: String::new(),
            turn_id: "t1".into(),
            session_id: "s1".into(),
            wire_api: wa::ANTHROPIC.into(),
            agent_kind: "claude-cli".into(),
            client_ip: "127.0.0.1".parse().unwrap(),
            server_ip: "127.0.0.1".parse().unwrap(),
            start_time_us: 0,
            end_time_us: 1_500_000,
            duration_ms: 1500,
            call_count: 3,
            models_used: vec!["claude-sonnet".into()],
            subagents_used: vec![],
            total_input_tokens: 100,
            total_output_tokens: 50,
            total_cache_read_input_tokens: 0,
            total_cache_creation_input_tokens: 0,
            total_cost_usd: None,
            status: TurnStatus::Complete,
            final_finish_reason: Some("complete".into()),
            user_input_preview: None,
            user_call_id: None,
            final_answer_preview: None,
            final_call_id: None,
            call_ids: vec![],
            metadata: serde_json::json!({}),
            tool_surfaces: vec![],
            tool_call_total: 0,
            agent_topology: None,
            suspicious_skills: vec![],
        };
        let s = turn.to_string();
        assert!(s.contains("t1"));
        assert!(s.contains("claude-cli"));
        assert!(s.contains("calls=3"));
        assert!(s.contains("complete"));
    }

    #[test]
    fn agent_turn_has_call_ids() {
        let turn = AgentTurn {
            source_id: String::new(),
            turn_id: "t".into(),
            session_id: "s".into(),
            wire_api: wa::ANTHROPIC.into(),
            agent_kind: "claude-cli".into(),
            client_ip: "127.0.0.1".parse().unwrap(),
            server_ip: "127.0.0.1".parse().unwrap(),
            start_time_us: 0,
            end_time_us: 0,
            duration_ms: 0,
            call_count: 2,
            models_used: vec![],
            subagents_used: vec![],
            total_input_tokens: 0,
            total_output_tokens: 0,
            total_cache_read_input_tokens: 0,
            total_cache_creation_input_tokens: 0,
            total_cost_usd: None,
            status: TurnStatus::Complete,
            final_finish_reason: None,
            user_input_preview: None,
            user_call_id: None,
            final_answer_preview: None,
            final_call_id: None,
            call_ids: vec!["call-1".into(), "call-2".into()],
            metadata: serde_json::json!({}),
            tool_surfaces: vec![],
            tool_call_total: 0,
            agent_topology: None,
            suspicious_skills: vec![],
        };
        assert_eq!(turn.call_ids.len(), 2);
        assert_eq!(turn.call_ids[0], "call-1");
    }
}
