use std::fmt;

/// Composite key identifying a single in-flight turn.
///
/// For Codex (explicit turn_id): both fields are Some.
/// For Anthropic (implicit): turn_id is generated by TurnTracker on turn start;
/// session_id comes from the X-Claude-Code-Session-Id header.
#[derive(Debug, Clone, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct TurnKey {
    pub stream_id: String,
    pub session_id: String,
    pub turn_id: String,
}

/// Terminal state of a turn.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TurnStatus {
    /// Saw explicit end signal (Anthropic end_turn, OpenAI stop, Responses message).
    Complete,
    /// Hit max_tokens / length.
    Length,
    /// Last call was an error and no retry arrived before finalize.
    Failed,
    /// Idle timeout, pcap EOF, or server shutdown before any end signal.
    Incomplete,
    /// Explicit user-initiated cancellation (connection RST mid-stream, etc.).
    Cancelled,
}

impl fmt::Display for TurnStatus {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            TurnStatus::Complete => write!(f, "complete"),
            TurnStatus::Length => write!(f, "length"),
            TurnStatus::Failed => write!(f, "failed"),
            TurnStatus::Incomplete => write!(f, "incomplete"),
            TurnStatus::Cancelled => write!(f, "cancelled"),
        }
    }
}

/// Aggregated record for one turn (user input → final assistant output).
#[derive(Debug, Clone)]
pub struct LlmTurn {
    pub stream_id: String,
    pub turn_id: String,
    pub session_id: String,
    pub tenant_id: Option<String>,
    pub provider: String,    // copied from LlmCall.provider
    pub client_kind: String, // "claude-cli" / "codex-cli" / ...

    pub start_time_us: i64, // first call's request_time
    pub end_time_us: i64,   // last call's complete_time (or request_time if no resp)
    pub duration_ms: u64,   // (end_time_us - start_time_us) / 1000

    pub call_count: u32,
    pub models_used: Vec<String>,    // ordered appearance, deduped
    pub subagents_used: Vec<String>, // ordered appearance, deduped; empty if none

    pub total_input_tokens: u64,
    pub total_output_tokens: u64,
    pub total_cache_read_input_tokens: u64,
    pub total_cache_creation_input_tokens: u64,
    pub total_cost_usd: Option<f64>, // None when pricing unknown

    pub status: TurnStatus,
    pub final_finish_reason: Option<String>, // FinishReason.to_string() of last call

    /// Up to ~500 chars of the user prompt that opened this turn. Full body
    /// lives on the `llm_calls` row pointed at by `user_call_id`.
    pub user_input_preview: Option<String>,
    /// LlmCall.id of the call whose request body carried the opening user
    /// prompt. `None` when profile could not extract user input.
    pub user_call_id: Option<String>,
    /// Up to ~500 chars of the final assistant text. Full body lives on
    /// `llm_calls` pointed at by `final_call_id`.
    pub final_answer_preview: Option<String>,
    /// LlmCall.id of the call that produced the terminating response.
    pub final_call_id: Option<String>,

    /// Ordered list of `LlmCall.id` values that belong to this turn.
    /// Populated by `TurnTracker::ingest` in ingest order. Replaces the
    /// Phase-1 `LlmCall.turn_id` back-reference.
    pub call_ids: Vec<String>,

    pub metadata: serde_json::Value, // future extension point; empty object by default
}

impl fmt::Display for LlmTurn {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            f,
            "[LlmTurn] turn={} session={} client={} calls={} dur={}ms status={}",
            self.turn_id,
            self.session_id,
            self.client_kind,
            self.call_count,
            self.duration_ms,
            self.status,
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use ts_llm::provider_names as pn;

    #[test]
    fn turn_key_equality_and_hash() {
        use std::collections::HashSet;
        let k1 = TurnKey {
            stream_id: String::new(),
            session_id: "s".into(),
            turn_id: "t".into(),
        };
        let k2 = TurnKey {
            stream_id: String::new(),
            session_id: "s".into(),
            turn_id: "t".into(),
        };
        let mut set = HashSet::new();
        set.insert(k1.clone());
        assert!(set.contains(&k2));
    }

    #[test]
    fn status_display() {
        assert_eq!(TurnStatus::Complete.to_string(), "complete");
        assert_eq!(TurnStatus::Incomplete.to_string(), "incomplete");
    }

    #[test]
    fn llm_turn_display_includes_key_fields() {
        let turn = LlmTurn {
            stream_id: String::new(),
            turn_id: "t1".into(),
            session_id: "s1".into(),
            tenant_id: None,
            provider: pn::ANTHROPIC.into(),
            client_kind: "claude-cli".into(),
            start_time_us: 0,
            end_time_us: 1_500_000,
            duration_ms: 1500,
            call_count: 3,
            models_used: vec!["claude-sonnet".into()],
            subagents_used: vec![],
            total_input_tokens: 100,
            total_output_tokens: 50,
            total_cache_read_input_tokens: 0,
            total_cache_creation_input_tokens: 0,
            total_cost_usd: None,
            status: TurnStatus::Complete,
            final_finish_reason: Some("complete".into()),
            user_input_preview: None,
            user_call_id: None,
            final_answer_preview: None,
            final_call_id: None,
            call_ids: vec![],
            metadata: serde_json::json!({}),
        };
        let s = turn.to_string();
        assert!(s.contains("t1"));
        assert!(s.contains("claude-cli"));
        assert!(s.contains("calls=3"));
        assert!(s.contains("complete"));
    }

    #[test]
    fn llm_turn_has_call_ids() {
        let turn = LlmTurn {
            stream_id: String::new(),
            turn_id: "t".into(),
            session_id: "s".into(),
            tenant_id: None,
            provider: pn::ANTHROPIC.into(),
            client_kind: "claude-cli".into(),
            start_time_us: 0,
            end_time_us: 0,
            duration_ms: 0,
            call_count: 2,
            models_used: vec![],
            subagents_used: vec![],
            total_input_tokens: 0,
            total_output_tokens: 0,
            total_cache_read_input_tokens: 0,
            total_cache_creation_input_tokens: 0,
            total_cost_usd: None,
            status: TurnStatus::Complete,
            final_finish_reason: None,
            user_input_preview: None,
            user_call_id: None,
            final_answer_preview: None,
            final_call_id: None,
            call_ids: vec!["call-1".into(), "call-2".into()],
            metadata: serde_json::json!({}),
        };
        assert_eq!(turn.call_ids.len(), 2);
        assert_eq!(turn.call_ids[0], "call-1");
    }
}
